name: improc_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - voila
  - itkwidgets
  - jupyterlab
  - nodejs
  - scikit-learn
  - rise
  - jupyter_contrib_nbextensions
  - pip:
    - napari
    - trackpy
    - tensorflow
    - keras
    - tqdm